import {
  CORE_FEAT_OPTIONS,
  createAbilityScoreImprovementFeature,
  createEpicBoonFeature,
  createSubclassChoiceFeature,
  toReferenceOptions,
  type CuratedFeatureReference,
  type CuratedLevelReference,
  type CuratedReferenceTuple,
  type CuratedSubclassOptionTuple,
  type CuratedSubclassReference,
} from "./curatedClassHelpers.js";

const ROGUE_FEAT_OPTIONS = CORE_FEAT_OPTIONS satisfies readonly CuratedReferenceTuple[];

const ROGUE_SKILL_OPTIONS = [
  ["skill-acrobatics", "Skill: Acrobatics"],
  ["skill-athletics", "Skill: Athletics"],
  ["skill-deception", "Skill: Deception"],
  ["skill-insight", "Skill: Insight"],
  ["skill-intimidation", "Skill: Intimidation"],
  ["skill-investigation", "Skill: Investigation"],
  ["skill-perception", "Skill: Perception"],
  ["skill-persuasion", "Skill: Persuasion"],
  ["skill-sleight-of-hand", "Skill: Sleight of Hand"],
  ["skill-stealth", "Skill: Stealth"],
] as const satisfies readonly CuratedReferenceTuple[];

const ALL_SKILL_OPTIONS = [
  ["skill-acrobatics", "Skill: Acrobatics"],
  ["skill-animal-handling", "Skill: Animal Handling"],
  ["skill-arcana", "Skill: Arcana"],
  ["skill-athletics", "Skill: Athletics"],
  ["skill-deception", "Skill: Deception"],
  ["skill-history", "Skill: History"],
  ["skill-insight", "Skill: Insight"],
  ["skill-intimidation", "Skill: Intimidation"],
  ["skill-investigation", "Skill: Investigation"],
  ["skill-medicine", "Skill: Medicine"],
  ["skill-nature", "Skill: Nature"],
  ["skill-perception", "Skill: Perception"],
  ["skill-performance", "Skill: Performance"],
  ["skill-persuasion", "Skill: Persuasion"],
  ["skill-religion", "Skill: Religion"],
  ["skill-sleight-of-hand", "Skill: Sleight of Hand"],
  ["skill-stealth", "Skill: Stealth"],
  ["skill-survival", "Skill: Survival"],
] as const satisfies readonly CuratedReferenceTuple[];

const ROGUE_LANGUAGE_OPTIONS = [
  ["common", "Common"],
  ["dwarvish", "Dwarvish"],
  ["elvish", "Elvish"],
  ["giant", "Giant"],
  ["gnomish", "Gnomish"],
  ["goblin", "Goblin"],
  ["halfling", "Halfling"],
  ["orc", "Orc"],
  ["abyssal", "Abyssal"],
  ["celestial", "Celestial"],
  ["draconic", "Draconic"],
  ["deep-speech", "Deep Speech"],
  ["infernal", "Infernal"],
  ["primordial", "Primordial"],
  ["sylvan", "Sylvan"],
  ["undercommon", "Undercommon"],
] as const satisfies readonly CuratedReferenceTuple[];

const ROGUE_SUBCLASSES = [
  ["arcane-trickster", "Arcane Trickster"],
  ["assassin", "Assassin"],
  ["soulknife", "Soulknife"],
  ["thief", "Thief"],
] as const satisfies readonly CuratedSubclassOptionTuple[];

const WEAPON_MASTERY_PROPERTY_OPTIONS = [
  "cleave",
  "graze",
  "nick",
  "push",
  "sap",
  "slow",
  "topple",
  "vex",
].map((index) => ({
  option_type: "reference",
  item: {
    index,
    name: index
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" "),
    url: `/api/2024/weapon-mastery-properties/${index}`,
  },
}));

function createSimpleFeature(
  index: string,
  level: number,
  name: string,
  ...desc: string[]
): CuratedFeatureReference {
  return {
    index,
    level,
    name,
    desc,
  };
}

function createSubclassFeature(
  index: string,
  level: number,
  name: string,
  subclassIndex: string,
  subclassName: string,
  ...desc: string[]
): CuratedFeatureReference {
  return {
    index,
    level,
    name,
    desc,
    subclass: {
      index: subclassIndex,
      name: subclassName,
      url: `/api/2024/subclasses/${subclassIndex}`,
    },
  };
}

function createRogueExpertiseFeature(index: string, level: number, description: string): CuratedFeatureReference {
  return {
    index,
    level,
    name: "Expertise",
    desc: [description],
    feature_specific: {
      choose: 2,
      type: "expertise",
      field_label: "Skill Expertise",
      from: {
        option_set_type: "options_array",
        options: toReferenceOptions(ALL_SKILL_OPTIONS, "proficiencies"),
      },
    },
  };
}

function toLanguageOptions(entries: readonly CuratedReferenceTuple[]) {
  return entries.map(([index, name]) => ({
    option_type: "reference",
    item: {
      index,
      name,
      url: `/api/2024/languages/${index}`,
    },
  }));
}

const ROGUE_FEATURE_REFERENCES: CuratedFeatureReference[] = [
  {
    index: "core-rogue-traits",
    level: 1,
    name: "Core Rogue Traits",
    desc: [
      "As a Level 1 Character:",
      "Gain all the traits in the Core Rogue Traits table.",
      "Gain the Rogue's level 1 features.",
    ],
    feature_specific: {
      choose: 4,
      type: "skill-proficiency",
      field_label: "Rogue Skill Proficiency",
      from: {
        option_set_type: "options_array",
        options: toReferenceOptions(ROGUE_SKILL_OPTIONS, "proficiencies"),
      },
    },
  },
  createRogueExpertiseFeature(
    "rogue-expertise-1",
    1,
    "You gain Expertise in two of your skill proficiencies of your choice.\n\nAt Rogue level 6, you gain Expertise in two more of your skill proficiencies of your choice.",
  ),
  createSimpleFeature(
    "sneak-attack",
    1,
    "Sneak Attack",
    "You know how to strike subtly and exploit a foe's distraction. Once per turn, you can deal an extra 1d6 damage to one creature you hit with an attack roll if you have Advantage on the roll and the attack uses a Finesse or a Ranged weapon. The extra damage's type is the same as the weapon's type.",
    "You don't need Advantage on the attack roll if at least one of your allies is within 5 feet of the target, the ally doesn't have the Incapacitated condition, and you don't have Disadvantage on the attack roll.",
    "The extra damage increases as you gain Rogue levels, as shown in the Sneak Attack column of the Rogue Features table.",
  ),
  {
    index: "thieves-cant",
    level: 1,
    name: "Thieves' Cant",
    desc: [
      "You picked up various languages in the communities where you plied your roguish talents. You know Thieves' Cant and one other language of your choice.",
    ],
    feature_specific: {
      choose: 1,
      type: "language",
      field_label: "Language",
      from: {
        option_set_type: "options_array",
        options: toLanguageOptions(ROGUE_LANGUAGE_OPTIONS),
      },
    },
  },
  {
    index: "rogue-weapon-mastery",
    level: 1,
    name: "Weapon Mastery",
    desc: [
      "Your training with weapons allows you to use the mastery properties of two kinds of weapons of your choice with which you have proficiency.",
      "Whenever you finish a Long Rest, you can change the kinds of weapons you chose.",
    ],
    feature_specific: {
      choose: 2,
      type: "weapon mastery",
      field_label: "Option",
      from: {
        option_set_type: "options_array",
        options: WEAPON_MASTERY_PROPERTY_OPTIONS,
      },
    },
  },
  createSimpleFeature(
    "cunning-action",
    2,
    "Cunning Action",
    "Your quick thinking and agility allow you to move and act quickly. On your turn, you can take one of the following actions as a Bonus Action: Dash, Disengage, or Hide.",
  ),
  createSubclassChoiceFeature(
    "rogue-subclass",
    3,
    "Rogue",
    ROGUE_SUBCLASSES,
    "You gain a Rogue subclass of your choice. A subclass is a specialization that grants you features at certain Rogue levels. For the rest of your career, you gain each of your subclass's features that are of your Rogue level or lower.",
  ),
  createSimpleFeature(
    "rogue-subclass-feature-3",
    3,
    "Subclass Feature",
    "Your chosen roguish archetype grants its defining 3rd-level features.",
  ),
  createSimpleFeature(
    "rogue-steady-aim",
    3,
    "Steady Aim",
    "As a Bonus Action, you give yourself Advantage on your next attack roll on the current turn. You can use this feature only if you haven't moved during this turn, and after you use it, your Speed is 0 until the end of the current turn.",
  ),
  createSubclassFeature(
    "arcane-trickster-spellcasting",
    3,
    "Spellcasting",
    "arcane-trickster",
    "Arcane Trickster",
    "You have learned to cast spells.",
    "Cantrips. You know three cantrips: Mage Hand and two other cantrips of your choice from the Wizard spell list.",
    "Whenever you gain a Rogue level, you can replace one of your cantrips, except Mage Hand, with another Wizard cantrip of your choice. When you reach Rogue level 10, you learn another Wizard cantrip of your choice.",
    "Spell Slots. The Arcane Trickster Spellcasting table shows how many spell slots you have to cast your level 1+ spells. You regain all expended spell slots when you finish a Long Rest.",
    "Arcane Trickster Spellcasting - Levels 3-6. Rogue 3: 3 prepared spells and 2 level 1 slots. Rogue 4-6: 4 prepared spells and 3 level 1 slots.",
    "Arcane Trickster Spellcasting - Levels 7-12. Rogue 7: 5 prepared spells, 4 level 1 slots, and 2 level 2 slots. Rogue 8-9: 6 prepared spells with the same slots. Rogue 10: 7 prepared spells, 4 level 1 slots, and 3 level 2 slots. Rogue 11-12: 8 prepared spells with the same slots.",
    "Arcane Trickster Spellcasting - Levels 13-20. Rogue 13: 9 prepared spells, 4 level 1 slots, 3 level 2 slots, and 2 level 3 slots. Rogue 14-15: 10 prepared spells with the same slots. Rogue 16-18: 11 prepared spells, 4 level 1 slots, 3 level 2 slots, and 3 level 3 slots. Rogue 19-20: 12 or more prepared spells, 4 level 1 slots, 3 level 2 slots, 3 level 3 slots, and 1 level 4 slot.",
    "Prepared Spells of Level 1+. You prepare the list of level 1+ spells that are available for you to cast with this feature. To start, choose three level 1 Wizard spells.",
    "The number of spells on your list increases as you gain Rogue levels, as shown in the Prepared Spells column of the Arcane Trickster Spellcasting table. The chosen spells must be of a level for which you have spell slots.",
    "Changing Your Prepared Spells. Whenever you gain a Rogue level, you can replace one spell on your list with another Wizard spell for which you have spell slots.",
    "Spellcasting Ability. Intelligence is your spellcasting ability for your Wizard spells.",
    "Spellcasting Focus. You can use an Arcane Focus as a Spellcasting Focus for your Wizard spells.",
  ),
  createSubclassFeature(
    "arcane-trickster-mage-hand-legerdemain",
    3,
    "Mage Hand Legerdemain",
    "arcane-trickster",
    "Arcane Trickster",
    "When you cast Mage Hand, you can cast it as a Bonus Action, and you can make the spectral hand Invisible. You can control the hand as a Bonus Action, and through it, you can make Dexterity (Sleight of Hand) checks.",
  ),
  createSubclassFeature(
    "assassinate",
    3,
    "Assassinate",
    "assassin",
    "Assassin",
    "You're adept at ambushing a target, granting you the following benefits.",
    "Initiative. You have Advantage on Initiative rolls.",
    "Surprising Strikes. During the first round of each combat, you have Advantage on attack rolls against any creature that hasn't taken a turn. If your Sneak Attack hits any target during that round, the target takes extra damage of the weapon's type equal to your Rogue level.",
  ),
  createSubclassFeature(
    "assassins-tools",
    3,
    "Assassin's Tools",
    "assassin",
    "Assassin",
    "You gain a Disguise Kit and a Poisoner's Kit, and you have proficiency with them.",
  ),
  createSubclassFeature(
    "psychic-blades",
    3,
    "Psychic Blades",
    "soulknife",
    "Soulknife",
    "You can manifest shimmering blades of psychic energy. Whenever you take the Attack action or make an Opportunity Attack, you can manifest a Psychic Blade in your free hand and make the attack with that blade. The magic blade has the following traits:",
    "Weapon Category: Simple Melee",
    "Damage on a Hit: 1d6 Psychic plus the ability modifier used for the attack roll",
    "Properties: Finesse, Thrown (range 60/120 feet)",
    "Mastery: Vex (you can use this property, and it doesn't count against the number of properties you can use with Weapon Mastery)",
    "The blade vanishes immediately after it hits or misses its target, and it leaves no mark if it deals damage.",
    "After you attack with the blade on your turn, you can make a melee or ranged attack with a second psychic blade as a Bonus Action on the same turn if your other hand is free to create it. The damage die of this bonus attack is 1d4 instead of 1d6.",
  ),
  createSubclassFeature(
    "psionic-power",
    3,
    "Psionic Power",
    "soulknife",
    "Soulknife",
    "You harbor a wellspring of psionic energy within yourself. It is represented by your Psionic Energy Dice, which fuel certain powers you have from this subclass. The Soulknife Energy Dice table shows the number of these dice you have when you reach certain Rogue levels, and the table shows the die size.",
    "Soulknife Energy Dice",
    "Rogue Level | Die Size | Number",
    "3 | D6 | 4",
    "5 | D8 | 6",
    "9 | D8 | 8",
    "11 | D10 | 8",
    "13 | D10 | 10",
    "17 | D12 | 12",
    "Any features in this subclass that use a Psionic Energy Die use only the dice from this subclass. Some of your powers expend a Psionic Energy Die, as specified in a power's description, and you can't use a power if it requires you to use a die when your Psionic Energy Dice are all expended.",
    "You regain one of your expended Psionic Energy Dice when you finish a Short Rest, and you regain all of them when you finish a Long Rest.",
    "Psi-Bolstered Knack. If you fail an ability check using a skill or tool with which you have proficiency, you can roll one Psionic Energy Die and add the number rolled to the check, potentially turning failure into success. The die is expended only if the roll then succeeds.",
    "Psychic Whispers. You can establish telepathic communication between yourself and others. As a Magic action, choose one or more creatures you can see, up to a number of creatures equal to your Proficiency Bonus, and then roll one Psionic Energy Die. For a number of hours equal to the number rolled, the chosen creatures can speak telepathically with you, and you can speak telepathically with them. To send or receive a message (no action required), you and the other creature must be within 1 mile of each other. A creature can end the telepathic connection at any time (no action required).",
    "The first time you use this power after each Long Rest, you don't expend the Psionic Energy Die. All other times you use the power, you expend the die.",
  ),
  createSubclassFeature(
    "fast-hands",
    3,
    "Fast Hands",
    "thief",
    "Thief",
    "As a Bonus Action, you can do one of the following.",
    "Sleight of Hand. Make a Dexterity (Sleight of Hand) check to pick a lock or disarm a trap with Thieves' Tools or to pick a pocket.",
    "Use an Object. Take the Utilize action, or take the Magic action to use a magic item that requires that action.",
  ),
  createSubclassFeature(
    "second-story-work",
    3,
    "Second-Story Work",
    "thief",
    "Thief",
    "You've trained to get into especially hard-to-reach places, granting you these benefits.",
    "Climber. You gain a Climb Speed equal to your Speed.",
    "Jumper. You can determine your jump distance using your Dexterity rather than your Strength.",
  ),
  createAbilityScoreImprovementFeature(
    "rogue-ability-score-improvement-1",
    4,
    ROGUE_FEAT_OPTIONS,
    "You gain the Ability Score Improvement feat or another feat of your choice for which you qualify. You gain this feature again at Rogue levels 8, 10, 12, and 16.",
  ),
  createSimpleFeature(
    "rogue-cunning-strike",
    5,
    "Cunning Strike",
    "You've developed cunning ways to use your Sneak Attack. When you deal Sneak Attack damage, you can add one of the following Cunning Strike effects. Each effect has a die cost, which is the number of Sneak Attack damage dice you must forgo to add the effect. You remove the die before rolling, and the effect occurs immediately after the attack's damage is dealt.",
    "If a Cunning Strike effect requires a saving throw, the DC equals 8 plus your Dexterity modifier and Proficiency Bonus.",
    "Poison (Cost: 1d6). You add a toxin to your strike, forcing the target to make a Constitution saving throw. On a failed save, the target has the Poisoned condition for 1 minute. At the end of each of its turns, the Poisoned target repeats the save, ending the effect on itself on a success. To use this effect, you must have a Poisoner's Kit on your person.",
    "Trip (Cost: 1d6). If the target is Large or smaller, it must succeed on a Dexterity saving throw or have the Prone condition.",
    "Withdraw (Cost: 1d6). Immediately after the attack, you move up to half your Speed without provoking Opportunity Attacks.",
  ),
  createSimpleFeature(
    "uncanny-dodge",
    5,
    "Uncanny Dodge",
    "When an attacker that you can see hits you with an attack roll, you can take a Reaction to halve the attack's damage against you (round down).",
  ),
  createRogueExpertiseFeature(
    "rogue-expertise-2",
    6,
    "You gain Expertise in two more of your skill proficiencies of your choice.",
  ),
  createSimpleFeature(
    "rogue-evasion",
    7,
    "Evasion",
    "You can nimbly dodge out of the way of certain dangers. When you're subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw and only half damage if you fail. You can't use this feature if you have the Incapacitated condition.",
  ),
  createSimpleFeature(
    "rogue-reliable-talent",
    7,
    "Reliable Talent",
    "Whenever you make an ability check that uses one of your skill or tool proficiencies, you can treat a d20 roll of 9 or lower as a 10.",
  ),
  createAbilityScoreImprovementFeature(
    "rogue-ability-score-improvement-2",
    8,
    ROGUE_FEAT_OPTIONS,
    "You gain the Ability Score Improvement feat or another feat of your choice for which you qualify. You gain this feature again at Rogue levels 10, 12, and 16.",
  ),
  createSimpleFeature(
    "rogue-subclass-feature-9",
    9,
    "Subclass Feature",
    "Your roguish archetype grants a 9th-level feature.",
  ),
  createSubclassFeature(
    "magical-ambush",
    9,
    "Magical Ambush",
    "arcane-trickster",
    "Arcane Trickster",
    "If you have the Invisible condition when you cast a spell on a creature, it has Disadvantage on any saving throw it makes against the spell on the same turn.",
  ),
  createSubclassFeature(
    "infiltration-expertise",
    9,
    "Infiltration Expertise",
    "assassin",
    "Assassin",
    "You are expert at the following techniques that aid your infiltrations.",
    "Masterful Mimicry. You can unerringly mimic another person's speech, handwriting, or both if you have spent at least 1 hour studying them.",
    "Roving Aim. Your Speed isn't reduced to 0 by using Steady Aim.",
  ),
  createSubclassFeature(
    "soul-blades",
    9,
    "Soul Blades",
    "soulknife",
    "Soulknife",
    "You can now use the following powers with your Psychic Blades.",
    "Homing Strikes. If you make an attack roll with your Psychic Blade and miss the target, you can roll one Psionic Energy Die and add the number rolled to the attack roll. If this causes the attack to hit, the die is expended.",
    "Psychic Teleportation. As a Bonus Action, you manifest a Psychic Blade, expend one Psionic Energy Die and roll it, and throw the blade at an unoccupied space you can see up to a number of feet away equal to 10 times the number rolled. You then teleport to that space, and the blade vanishes.",
  ),
  createSubclassFeature(
    "supreme-sneak",
    9,
    "Supreme Sneak",
    "thief",
    "Thief",
    "You gain the following Cunning Strike option.",
    "Stealth Attack (Cost: 1d6). If you have the Hide action's Invisible condition, this attack doesn't end that condition on you if you end the turn behind Three-Quarters Cover or Total Cover.",
  ),
  createAbilityScoreImprovementFeature(
    "rogue-ability-score-improvement-3",
    10,
    ROGUE_FEAT_OPTIONS,
    "You gain the Ability Score Improvement feat or another feat of your choice for which you qualify. You gain this feature again at Rogue levels 12 and 16.",
  ),
  createSimpleFeature(
    "rogue-improved-cunning-strike",
    11,
    "Improved Cunning Strike",
    "You can use up to two Cunning Strike effects when you deal Sneak Attack damage, paying the die cost for each effect.",
  ),
  createAbilityScoreImprovementFeature(
    "rogue-ability-score-improvement-4",
    12,
    ROGUE_FEAT_OPTIONS,
    "You gain the Ability Score Improvement feat or another feat of your choice for which you qualify. You gain this feature again at Rogue level 16.",
  ),
  createSimpleFeature(
    "rogue-subclass-feature-13",
    13,
    "Subclass Feature",
    "Your roguish archetype grants a 13th-level feature.",
  ),
  createSubclassFeature(
    "versatile-trickster",
    13,
    "Versatile Trickster",
    "arcane-trickster",
    "Arcane Trickster",
    "You gain the ability to distract targets with your Mage Hand. When you use the Trip option of your Cunning Strike on a creature, you can also use that option on another creature within 5 feet of the spectral hand.",
  ),
  createSubclassFeature(
    "envenom-weapons",
    13,
    "Envenom Weapons",
    "assassin",
    "Assassin",
    "When you use the Poison option of your Cunning Strike, the target also takes 2d6 Poison damage whenever it fails the saving throw. This damage ignores Resistance to Poison damage.",
  ),
  createSubclassFeature(
    "psychic-veil",
    13,
    "Psychic Veil",
    "soulknife",
    "Soulknife",
    "You can weave a veil of psychic static to mask yourself. As a Magic action, you gain the Invisible condition for 1 hour or until you dismiss this effect (no action required). This invisibility ends early immediately after you deal damage to a creature or you force a creature to make a saving throw.",
    "Once you use this feature, you can't do so again until you finish a Long Rest unless you expend a Psionic Energy Die (no action required) to restore your use of it.",
  ),
  createSubclassFeature(
    "use-magic-device",
    13,
    "Use Magic Device",
    "thief",
    "Thief",
    "You've learned how to maximize use of magic items, granting you the following benefits.",
    "Attunement. You can attune to up to four magic items at once.",
    "Charges. Whenever you use a magic item property that expends charges, roll 1d6. On a roll of 6, you use the property without expending the charges.",
    "Scrolls. You can use any Spell Scroll, using Intelligence as your spellcasting ability for the spell. If the spell is a cantrip or a level 1 spell, you can cast it reliably. If the scroll contains a higher-level spell, you must first succeed on an Intelligence (Arcana) check (DC 10 plus the spell's level). On a successful check, you cast the spell from the scroll. On a failed check, the scroll disintegrates.",
  ),
  createSimpleFeature(
    "rogue-devious-strikes",
    14,
    "Devious Strikes",
    "You've practiced new ways to use your Sneak Attack deviously. The following effects are now among your Cunning Strike options.",
    "Daze (Cost: 2d6). The target must succeed on a Constitution saving throw, or on its next turn, it can do only one of the following: move or take an action or a Bonus Action.",
    "Knock Out (Cost: 6d6). The target must succeed on a Constitution saving throw, or it has the Unconscious condition for 1 minute or until it takes any damage. The Unconscious target repeats the save at the end of each of its turns, ending the effect on itself on a success.",
    "Obscure (Cost: 3d6). The target must succeed on a Dexterity saving throw, or it has the Blinded condition until the end of its next turn.",
  ),
  createSimpleFeature(
    "slippery-mind",
    15,
    "Slippery Mind",
    "Your cunning mind is exceptionally difficult to control. You gain proficiency in Wisdom and Charisma saving throws.",
  ),
  createAbilityScoreImprovementFeature(
    "rogue-ability-score-improvement-5",
    16,
    ROGUE_FEAT_OPTIONS,
    "You gain the Ability Score Improvement feat or another feat of your choice for which you qualify.",
  ),
  createSimpleFeature(
    "rogue-subclass-feature-17",
    17,
    "Subclass Feature",
    "Your roguish archetype grants a 17th-level feature.",
  ),
  createSubclassFeature(
    "spell-thief",
    17,
    "Spell Thief",
    "arcane-trickster",
    "Arcane Trickster",
    "You gain the ability to magically steal the knowledge of how to cast a spell from another spellcaster.",
    "Immediately after a creature casts a spell that targets you or includes you in its area of effect, you can take a Reaction to force the creature to make an Intelligence saving throw. The DC equals your spell save DC. On a failed save, you negate the spell's effect against you, and you steal the knowledge of the spell if it is at least level 1 and of a level you can cast. For the next 8 hours, you have the spell prepared. The creature can't cast it until the 8 hours have passed.",
    "Once you steal a spell with this feature, you can't use this feature again until you finish a Long Rest.",
  ),
  createSubclassFeature(
    "death-strike",
    17,
    "Death Strike",
    "assassin",
    "Assassin",
    "When you hit with your Sneak Attack on the first round of a combat, the target must succeed on a Constitution saving throw (DC 8 plus your Dexterity modifier and Proficiency Bonus), or the attack's damage is doubled against the target.",
  ),
  createSubclassFeature(
    "rend-mind",
    17,
    "Rend Mind",
    "soulknife",
    "Soulknife",
    "You can sweep your Psychic Blades through a creature's mind. When you use your Psychic Blades to deal Sneak Attack damage to a creature, you can force that target to make a Wisdom saving throw (DC 8 plus your Dexterity modifier and Proficiency Bonus). If the save fails, the target has the Stunned condition for 1 minute. The Stunned target repeats the save at the end of each of its turns, ending the effect on itself on a success.",
    "Once you use this feature, you can't do so again until you finish a Long Rest unless you expend three Psionic Energy Dice (no action required) to restore your use of it.",
  ),
  createSubclassFeature(
    "thiefs-reflexes",
    17,
    "Thief's Reflexes",
    "thief",
    "Thief",
    "You are adept at laying ambushes and quickly escaping danger. You can take two turns during the first round of any combat. You take your first turn at your normal Initiative and your second turn at your Initiative minus 10.",
  ),
  createSimpleFeature(
    "elusive",
    18,
    "Elusive",
    "You're so evasive that attackers rarely gain the upper hand against you. No attack roll can have Advantage against you unless you have the Incapacitated condition.",
  ),
  createEpicBoonFeature("rogue-epic-boon", 19),
  createSimpleFeature(
    "stroke-of-luck",
    20,
    "Stroke of Luck",
    "You have a marvelous knack for succeeding when you need to. If you fail a D20 Test, you can turn the roll into a 20.",
    "Once you use this feature, you can't use it again until you finish a Short or Long Rest.",
  ),
];

const ROGUE_LEVEL_REFERENCES: CuratedLevelReference[] = [
  {
    index: "rogue-1",
    level: 1,
    features: ["core-rogue-traits", "rogue-expertise-1", "sneak-attack", "thieves-cant", "rogue-weapon-mastery"],
  },
  { index: "rogue-2", level: 2, features: ["cunning-action"] },
  {
    index: "rogue-3",
    level: 3,
    features: [
      "rogue-subclass",
      "rogue-subclass-feature-3",
      "rogue-steady-aim",
      "arcane-trickster-spellcasting",
      "arcane-trickster-mage-hand-legerdemain",
      "assassinate",
      "assassins-tools",
      "psychic-blades",
      "psionic-power",
      "fast-hands",
      "second-story-work",
    ],
  },
  { index: "rogue-4", level: 4, features: ["rogue-ability-score-improvement-1"] },
  { index: "rogue-5", level: 5, features: ["rogue-cunning-strike", "uncanny-dodge"] },
  { index: "rogue-6", level: 6, features: ["rogue-expertise-2"] },
  { index: "rogue-7", level: 7, features: ["rogue-evasion", "rogue-reliable-talent"] },
  { index: "rogue-8", level: 8, features: ["rogue-ability-score-improvement-2"] },
  {
    index: "rogue-9",
    level: 9,
    features: ["rogue-subclass-feature-9", "magical-ambush", "infiltration-expertise", "soul-blades", "supreme-sneak"],
  },
  { index: "rogue-10", level: 10, features: ["rogue-ability-score-improvement-3"] },
  { index: "rogue-11", level: 11, features: ["rogue-improved-cunning-strike"] },
  { index: "rogue-12", level: 12, features: ["rogue-ability-score-improvement-4"] },
  {
    index: "rogue-13",
    level: 13,
    features: ["rogue-subclass-feature-13", "versatile-trickster", "envenom-weapons", "psychic-veil", "use-magic-device"],
  },
  { index: "rogue-14", level: 14, features: ["rogue-devious-strikes"] },
  { index: "rogue-15", level: 15, features: ["slippery-mind"] },
  { index: "rogue-16", level: 16, features: ["rogue-ability-score-improvement-5"] },
  {
    index: "rogue-17",
    level: 17,
    features: ["rogue-subclass-feature-17", "spell-thief", "death-strike", "rend-mind", "thiefs-reflexes"],
  },
  { index: "rogue-18", level: 18, features: ["elusive"] },
  { index: "rogue-19", level: 19, features: ["rogue-epic-boon"] },
  { index: "rogue-20", level: 20, features: ["stroke-of-luck"] },
];

const ROGUE_SUBCLASS_REFERENCES: CuratedSubclassReference[] = [
  {
    index: "arcane-trickster",
    name: "Arcane Trickster",
    subclass_flavor: "Arcane Trickster",
    summary: "Enhance Stealth with Arcane Spells",
    description:
      "Some Rogues enhance their fine-honed skills of stealth and agility with spells, learning magical tricks to aid them in their trade.",
    features: [
      { name: "Spellcasting", level: 3, description: "You have learned to cast Wizard spells through Arcane Trickster magic." },
      { name: "Mage Hand Legerdemain", level: 3, description: "Your Mage Hand becomes invisible, faster, and useful for Sleight of Hand tricks." },
      { name: "Magical Ambush", level: 9, description: "Invisible spellcasting makes your targets worse at resisting your spells." },
      { name: "Versatile Trickster", level: 13, description: "Your Mage Hand can help spread the Trip option of your Cunning Strike." },
      { name: "Spell Thief", level: 17, description: "You can negate and temporarily steal another spellcaster's spell." },
    ],
  },
  {
    index: "assassin",
    name: "Assassin",
    subclass_flavor: "Assassin",
    summary: "Perfect ambush, infiltration, and lethal first-round pressure",
    description: "Assassins specialize in ambush, infiltration, poisoncraft, and decisive opening strikes.",
    features: [
      { name: "Assassinate", level: 3, description: "You gain Advantage on Initiative and first-round attacks against creatures that have not acted yet." },
      { name: "Assassin's Tools", level: 3, description: "You gain a Disguise Kit and Poisoner's Kit, and proficiency with both." },
      { name: "Infiltration Expertise", level: 9, description: "You master mimicry and can keep moving when you use Steady Aim." },
      { name: "Envenom Weapons", level: 13, description: "Your Poison Cunning Strike deals extra Poison damage that ignores Resistance." },
      { name: "Death Strike", level: 17, description: "Your first-round Sneak Attack can double its damage against a failed Constitution save." },
    ],
  },
  {
    index: "soulknife",
    name: "Soulknife",
    subclass_flavor: "Soulknife",
    summary: "Manifest psionic blades and strike mind-first",
    description: "Soulknives shape psychic force into blades, telepathic coordination, psionic mobility, and mind-rending precision.",
    features: [
      { name: "Psionic Power", level: 3, description: "You gain Psionic Energy Dice for Psi-Bolstered Knack and Psychic Whispers." },
      { name: "Psychic Blades", level: 3, description: "You manifest finesse, thrown psychic blades and can make a second blade attack as a Bonus Action." },
      { name: "Soul Blades", level: 9, description: "Your Psychic Blades gain Homing Strikes and Psychic Teleportation." },
      { name: "Psychic Veil", level: 13, description: "You can become Invisible for 1 hour, with later uses restored by Psionic Energy Dice." },
      { name: "Rend Mind", level: 17, description: "Your Psychic Blades can leave a Sneak Attack target Stunned." },
    ],
  },
  {
    index: "thief",
    name: "Thief",
    subclass_flavor: "Thief",
    summary: "Do the impossible through speed, utility, and nerve",
    description: "Thieves are consummate opportunists who solve problems through movement, improvisation, and audacious use of gear and space.",
    features: [
      { name: "Fast Hands", level: 3, description: "You can use Sleight of Hand or use certain objects and magic items as a Bonus Action." },
      { name: "Second-Story Work", level: 3, description: "You gain a Climb Speed equal to your Speed and can use Dexterity for jump distance." },
      { name: "Supreme Sneak", level: 9, description: "You gain the Stealth Attack Cunning Strike option." },
      { name: "Use Magic Device", level: 13, description: "You can attune to four magic items, conserve charges, and use Spell Scrolls with Intelligence." },
      { name: "Thief's Reflexes", level: 17, description: "You take two turns during the first round of combat." },
    ],
  },
];

const ROGUE_CURATED_2024_CLASS_OVERRIDE = {
  classIndex: "rogue",
  className: "Rogue",
  subclasses: ROGUE_SUBCLASSES,
  featureReferences: ROGUE_FEATURE_REFERENCES,
  levelReferences: ROGUE_LEVEL_REFERENCES,
  subclassReferences: ROGUE_SUBCLASS_REFERENCES,
};

export { ROGUE_CURATED_2024_CLASS_OVERRIDE };
